##.libPaths()
##installed.packages()
#library(grid)
#grid.newpage()
#grid.lines()

#require()
#install.packages("xts", dependencies = TRUE)
#library(xts)
#install.packages("zoo", dependencies = TRUE)
#sessionInfo()
update.packages()
#library(randtoolbox)
#help(package = "xts")
